### ISSUE TITLE
OPTIONS/GET /location/<slug> sets active model's location

### ISSUE THREAD

**Issue by daf** [NOAA-ORR-ERD/WebGnomeAPI#1]
Looking at communication in WebGnomeClient back to the server (WebGnomeAPI), simply making an OPTIONS request (as many single-page-applications do) to a location URL with a location slug set will set that location for the model.  It does this again on the GET request that immediately follows.  I would not expect either of these calls to modify anything - would expect idempotency.

The problematic code is in [`location.py/load_location_file`](https://github.com/NOAA-ORR-ERD/WebGnomeAPI/blob/2e4b5989eb14a43da2d138a0737150e0fd7c3f26/webgnome_api/views/location.py#L77-L101)

Can provide screenshots of inspector traces if that helps.

**Comment by ChrisBarker-NOAA** [comment]
I presume this has been resolved (or not) by  now
