### ISSUE TITLE
What is the corresponding version of PyGnome for WebGnomeAPI?

### ISSUE THREAD

**Issue by jjYukgm** [NOAA-ORR-ERD/WebGnomeAPI#4]
I try to build the WebGnomeAPI with my local machine, ubuntu-18.04 with venv python2.7 in anaconda3.
Following the readme file, I setup the package and do the test.
But, it seems the corresponding version of PyGnome is older than the now one.
There is no module / attribute in PyGnome named : 
> gnome.spill.release.ContinuousRelease
> gnome.movers.random_movers.RandomVerticalMover 
> gnome.spill.elements.ElementType

But, the py-test scription of WebGnomeAPI still try to call the attributes.
Is there any updated version of WebGnomeAPI?
Does the package need being built up in python3.6+?

**Comment by ChrisBarker-NOAA** [comment]
Sorry -- we have been REALLY bad at keeping this repo updated.

As a rule, the branch in this repo and in Py_gnome (and OilLibrary, and ...) should all be in sync.

So if you use master in one, you should use master in all the others. 

At this point:
 - master is using Python2.7, and the most stable 
 - develop is using Python3.8, and is *almost* stable enough for us to merge to master
 
So I recommend develop for any new work, but make sure it's been updated recently.

I'll be pushing updated soon.

Thanks for your patience, ann the report!

**Comment by ChrisBarker-NOAA** [comment]
OK -- all repos should be updated -- please post another issue if you have problems.
