### ISSUE TITLE
Can't start the server

### ISSUE THREAD

**Issue by hawklorry** [NOAA-ORR-ERD/WebGnomeAPI#6]
I got following message when I tried to start the server. Is adios_db a required package? It's not list in the requirement list. And the server is tested OK. Could you please advise? I'm using the develop branch. 

pserve config-example.ini
C:\Users\CA-Modeller\Anaconda3\envs\WebGnome\lib\site-packages\pygnome-1.1.0-py3.8-win-amd64.egg\gnome\__init__.py:50: UserWarning: ERROR: The adios_db package, version >= 0.6.0 needs to be installed
  warnings.warn(msg)
Starting server in PID 8840.

**Comment by ChrisBarker-NOAA** [comment]
ouch! sorry. We do our development on an internal system, and have been really bad at keeping the gitHub version up to date.
I'll see. if I can update now.
As a rule, you want to use the same branch on all three components: all master or all develop -- we do try to keep those in sync.

**Comment by ChrisBarker-NOAA** [comment]
OK -- master and develop should be up to date for all three projects.

**Comment by hawklorry** [comment]
Awesome! Thanks so much @ChrisBarker-NOAA. 

For all three components, do you mean pynome, WebGnomeAPI and WebGnomeClient? I think we also need oil library and oil library api. Are they also in sync? 

I'm also wondering what tools you guys are using for debugging WebGnomeClient (backbone.js) and WebGnomeAPI (Pyramid). Is there a guidance document you could share?

**Comment by hawklorry** [comment]
Thanks @ChrisBarker-NOAA . This has been very helpful. I will close the issues. Hopefully to see the new version come online soon.
