### ISSUE TITLE
Which branch is the latest? 

### ISSUE THREAD

**Issue by hawklorry** [NOAA-ORR-ERD/WebGnomeAPI#7]
@ChrisBarker-NOAA We are kicking-off another phase of customization and plan to get the latest source codes for all components (PyGNOME, WebGnomeAPI and WebGnomeClient). Could you please advise which branch we should use? I noticed that develop branch isn't always the latest.

**Comment by ChrisBarker-NOAA** [comment]
We do are development in an internal git system, and only push to gitHub sporadically, so you're asking here is a good idea.

Once I push, develop is the latest, main should be stable, and production is the "released" version (i.e. the one we use for gnome.orr.noaa.gov).

In practice:

develop is the latest, but not well tested yet.

main should be stable, and not changed often

production is little different then main, but does change less.

NOTE: we are under active development of the "Use Operational Forecasts" features -- this allows the user to pull current, winds, etc from operational models. 

However, this depends on some pretty unreliable external services, so it's pretty flaky, and the code on the back end is changing fast.

I'll update the projects now ...

**Comment by ChrisBarker-NOAA** [comment]
OK -- develop, main, and production are all up to date in:
- PyGNOME
- WebGnomeAPI
 - WebGnomeClient

NOTE: you should use the same branch on all three in order for them to work together.

**Comment by hawklorry** [comment]
Thank you very much @ChrisBarker-NOAA . Could you please give more details on the "Use Operational Forecasts" features?
